blog/urls.py
from django.urls import path
from .views import * 

urlpatterns = [
    path('' , blog , name="blog"),
    path('blog/<slug>' , blog_d , name="blog_detail"),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('booking.urls', 'booking'), namespace='booking')),
    path('ecom', include(('ecom.urls', 'ecom'), namespace='ecom')),
    path('blog', include(('blog.urls', 'blog'), namespace='blog')),
    path('accounts/', include('django.contrib.auth.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.utils.text import slugify

class Blog(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField()
    content = models.TextField(blank=True)
    slug = models.SlugField(unique=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Blog, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render,redirect
from .models import *

def blog(request):
    blogs = Blog.objects.all()

    return render(request, 'blog/blog_page.html', {'blogs': blogs})


def blog_d(request, slug):
    post = Blog.objects.filter(slug = slug).first()
    return render(request , 'blog/blog_detail.html' , {'post': post})

templates/blog/blog_detail.html
{%include "base.html"%}

<img src="/media/{{post.image}}" alt=""><br><br>
{{post.title}}<br><br>
{{post.content}}<br><br>
{{ blogs.created_at }}
{%include "footer.html"%}

templates/blog/blog_page.html
{%include "base.html"%}




{% for blogs in blogs %}
<img class="img-thumbnail" src="/media/{{blogs.image}}" alt="Card image cap">
<a href="{% url 'blog:blog_detail' blogs.slug %}">{{ blogs.title }}</a>
{{ blogs.content }}
{{ blogs.created_at }}

{% endfor %}


{%include "footer.html"%}