blog/urls.py
from django.urls import path
from .views import * 

urlpatterns = [
    path('' , blog , name="blog"),
    path('blog/<slug>' , blog_d , name="blog_detail"),
]

booking/urls.py
from django.urls import path
from .views import * 

urlpatterns = [
    path('services/' , serv , name="services"),
    path('services/<slug>' , serv_d , name="services_detail"),
    path('accounts/register/', register, name='register'),
    path('contact/', Contact, name='contact'),
    path('about/', about, name='about'),
    path('', home, name='home'),
    path('checkout/', checkout, name='checkout'),
    path('orders/', orders, name='orders'),
    path('search/', search, name='search'),
    path('faq/', faq, name='faq'),
    path('legal/', legal, name='legal'),
    path('terms/', terms, name='terms'),
    path('privacy-policy/', privacy_policy, name='privacy_policy'),


]

main/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('booking.urls', 'booking'), namespace='booking')),
    path('ecom', include(('ecom.urls', 'ecom'), namespace='ecom')),
    path('blog', include(('blog.urls', 'blog'), namespace='blog')),
    path('accounts/', include('django.contrib.auth.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static%}




  <link rel="shortcut icon" href="{% static 'images/favicon.png'%}" type="image/x-icon">
	<link rel="icon" href="{% static 'images/favicon.png'%}" type="image/x-icon">

	<!-- # Google Fonts -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;700&display=swap" rel="stylesheet">

	<!-- # CSS Plugins -->
	<link rel="stylesheet" href="{% static 'plugins/slick/slick.css'%}">
	<link rel="stylesheet" href="{% static 'plugins/font-awesome/fontawesome.min.css'%}">
	<link rel="stylesheet" href="{% static 'plugins/font-awesome/brands.css'%}">
	<link rel="stylesheet" href="{% static 'plugins/font-awesome/solid.css'%}">
	<script src="https://kit.fontawesome.com/f78f41b9a4.js" crossorigin="anonymous"></script>
	<!-- # Main Style Sheet -->
	<link rel="stylesheet" href="{% static 'css/style.css'%}">

  <!-- slider css -->

  <link rel="stylesheet" href="fonts/icomoon/style.css'%}">
<link rel="stylesheet" href="{% static 'service-css/owl.carousel.min.css'%}">
<link rel="stylesheet" href="{% static 'service-css/style.css'%}">

  <!-- slider css -->

  <!-- search css -->
  <link rel="stylesheet" href="{% static 'search-css/main.css'%}">

  <!-- search css -->




                                <script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>

</head>
<style>

p{
  font-size: 18px;
  color: black;
  font-weight: 400;
}

	.content{
	  padding-top: 20px;
	  padding-bottom: 20px;
	}
	
	</style>
<body>

<!-- navigation -->
<header class="navigation bg-tertiary">
	<nav class="navbar navbar-expand-xl navbar-light text-center py-3">
		<div class="container">
			<a class="navbar-brand" href="{% url 'booking:home' %}">
				<img loading="prelaod" decoding="async" class="img-fluid" width="160" src="{% static 'images/logooo.png'%}" alt="Wallet">
			</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mx-auto mb-2 mb-lg-0">
					<li class="nav-item"> <a class="nav-link" href="{% url 'booking:home' %}">Home</a>
					</li>
					<li class="nav-item "> <a class="nav-link" href="{% url 'booking:about' %}">About</a>
          </li>
					<li class="nav-item "> <a class="nav-link" href="{% url 'booking:orders' %}">Orders</a>
          </li>
					<li class="nav-item "> <a class="nav-link" href="{% url 'booking:services' %}">Services</a>
					</li>
					<li class="nav-item "> <a class="nav-link" href="{% url 'booking:contact' %}">Contact</a>
					</li>
					

				</ul>



          {% if user.is_authenticated %}


        <!-- account btn --> <a href="{% url 'booking:orders' %}" class="btn btn-outline-primary">{{ user.get_username }}</a>
				<!-- account btn --> <a href="{% url 'logout' %}?next=/accounts/login/" class="btn btn-primary ms-2 ms-lg-3">Log Out</a>

           

          {% else %}


          				<!-- account btn --> <a href="{% url 'login' %}" class="btn btn-outline-primary">Log In</a>
				<!-- account btn --> <a href="{% url 'booking:register' %}" class="btn btn-primary ms-2 ms-lg-3">Sign Up</a>

          {% endif %}
      

	
			</div>
		</div>
	</nav>
</header>




  

  
  </body>
  </html>



<!-- /navigation -->

templates/checkout.html
{%include "base.html"%}

<h1>Checkout</h1>

{%include "footer.html"%}

templates/contact.html
{%include "base.html"%}
{% load crispy_forms_tags %} 





  
  <section class="section">
      <div class="container">
          <div class="row justify-content-center align-items-center">
              <div class="col-lg-6">
                  <div class="section-title text-center">
                      <p class="text-primary text-uppercase fw-bold mb-3">Contact With us</p>
                      <h1>let&rsquo;s get connected</h1>
                      <p>Lorem ipsum dolor sit, consectetur adipiscing . egestas cursus pellentesque dignissim dui, congue etiam</p>
                  </div>
              </div>
              <div class="col-lg-10">
                  <div class="shadow rounded p-5 bg-white">
                      <div class="row">
                          <div class="col-12 mb-4">
                              <h4>Leave Us A Message</h4>
                          </div>
                          <div class="col-lg-6">
                              <div class="contact-form">
                                <form action="" method="post">
                                    {% csrf_token %}

                                      <div class="form-group mb-4 pb-2">
                                          {{form.name|as_crispy_field}}
                                      </div>

                                      <div class="form-group mb-4 pb-2">
                                        {{form.email|as_crispy_field}}
                                      </div>

                                      <div class="form-group mb-4 pb-2">
                                        {{form.phone_no|as_crispy_field}}
                                      </div>
                                      <div class="form-group mb-4 pb-2">
                                        {{form.message|as_crispy_field}}
                                      </div>

                                      <input class="btn btn-primary w-100" type="submit" value="Submit">

                                  </form>
                              </div>
                          </div>
                          <div class="col-lg-6 mt-5 mt-lg-0">
                              <div class="contact-info">
                                  <div class="block mt-0">
                                      <h4 class="h5">Still Have Questions?</h4>
                                      <div class="content">Call Us We Will Be Happy To Help
                                          <br> <a href="tel:+3301563965">+123456789</a> 
                                          <br>Monday - Friday
                                          <br>9AM TO 8PM Eastern Time</div>
                                  </div>
                                  <div class="block mt-4">
                                      <h4 class="h5">Chattisgarh</h4>
                                      <div class="content">231 Ross Street.
                                          <br>K7A 1C2.
                                          <br>Smiths Falls</div>
                                  </div>
                                  <div class="block mt-4">
                                      <h4 class="h5">madhyapradesh</h4>
                                      <div class="content">57 Folkestone Road.
                                          <br>AB54 5XQ,
                                          <br>Winston</div>
                                  </div>
                                  <div class="block">
                                      <ul class="list-unstyled list-inline my-4 social-icons">
                                          <li class="list-inline-item me-3"><a title="Explorer Facebook Profile" class="text-black" href="https://facebook.com/"><i class="fab fa-facebook-f"></i></a>
                                          </li>
                                          <li class="list-inline-item me-3"><a title="Explorer Twitter Profile" class="text-black" href="https://twitter.com/"><i class="fab fa-twitter"></i></a>
                                          </li>
                                          <li class="list-inline-item me-3"><a title="Explorer Instagram Profile" class="text-black" href="https://instagram.com/"><i class="fab fa-instagram"></i></a>
                                          </li>
                                      </ul>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </section>
  {%include "footer.html"%}

templates/footer.html
{% load static%}


<style>

.footer-link{
    color: white !important;
}

</style>

<footer style="background-color: #262626;" class="section-sm ">
    <div class="container">
        <div class="row justify-content-between">
            <div class="col-lg-2 col-md-4 col-6 mb-4">
                <div class="footer-widget">
                    <h5 class="mb-4 text-primary font-secondary">Service</h5>
                    <ul  class="list-unstyled">
                        <li class="mb-2"><a class="footer-link" href="service-details.html">Personal loans</a>
                        </li>
                        <li class="mb-2"><a class="footer-link" href="service-details.html">Home Equity Loans</a>
                        </li>
                        <li class="mb-2"><a class="footer-link" href="service-details.html">Student Loans</a>
                        </li>
                        <li class="mb-2"><a class="footer-link"  href="service-details.html">Mortgage Loans</a>
                        </li>
                        <li class="mb-2"><a class="footer-link" href="service-details.html">Payday Loans</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-6 mb-4">
                <div class="footer-widget">
                    <h5 class="mb-4 text-primary font-secondary">About</h5>
                    <ul class="list-unstyled">
                        <li class="mb-2"><a class="footer-link" href="#!">Benefits</a>
                        </li>
                        <li class="mb-2"><a class="footer-link" href="#!">Careers</a>
                        </li>
                        <li class="mb-2"><a class="footer-link" href="#!">Our Story</a>
                        </li>
                        <li class="mb-2"><a class="footer-link" href="#!">Team</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-6 mb-4">
                <div class="footer-widget">
                    <h5 class="mb-4 text-primary font-secondary">Help</h5>
                    <ul class="list-unstyled">
                        <li class="mb-2"><a class="footer-link" href="contact.html">Contact Us</a>
                        </li>
                        <li class="mb-2"><a class="footer-link" href="faq.html">FAQs</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-12 newsletter-form">
                <div style="background-color: #262626; padding: 35px;">
                    <h5 class="mb-4 text-primary font-secondary">Contact us</h5>
                    






                    <p style="color: white;" class="mb-0">Lorem ipsum dolor sit amet, rdghds consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat</p>
                </div>
            </div>
        </div>
        <div class="row align-items-center mt-5 text-center text-md-start">
            <div class="col-lg-4">
        <a href="index.html">
          <img loading="prelaod" decoding="async" class="img-fluid" width="160" src="{% static 'images/logooo.png'%}" alt="Wallet">
        </a>
            </div>
            <div class="col-lg-4 col-md-6 mt-4 mt-lg-0">
                <ul class="list-unstyled list-inline mb-0 text-lg-center">
                    <li class="list-inline-item me-4"><a  href="privacy-policy.html">Privacy Policy</a>
                    </li>
                    <li class="list-inline-item me-4"><a  href="terms.html">Terms &amp; Conditions</a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-4 col-md-6 text-md-end mt-4 mt-md-0">
                <ul class="list-unstyled list-inline mb-0 social-icons">
                    <li class="list-inline-item me-3"><a title="Explorer Facebook Profile"  href="https://facebook.com/"><i class="fab fa-facebook-f"></i></a>
                    </li>
                    <li class="list-inline-item me-3"><a title="Explorer Twitter Profile"  href="https://twitter.com/"><i class="fab fa-twitter"></i></a>
                    </li>
                    <li class="list-inline-item me-3"><a title="Explorer Instagram Profile" href="https://instagram.com/"><i class="fab fa-instagram"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>


<!-- # JS Plugins -->
<script src="{% static 'plugins/jquery/jquery.min.js'%}"></script>
<script src="{% static 'plugins/bootstrap/bootstrap.min.js'%}"></script>
<script src="{% static 'plugins/slick/slick.min.js'%}"></script>
<script src="{% static 'plugins/scrollmenu/scrollmenu.min.js'%}"></script>

<script src="js/script.js'%}"></script>
<!-- Main Script -->


<!-- slider script -->
<script src="{% static 'service-js/jquery-3.3.1.min.js'%}"></script>
<script src="{% static 'service-js/popper.min.js'%}"></script>
<script src="{% static 'service-js/bootstrap.min.js'%}"></script>
<script src="{% static 'service-js/owl.carousel.min.js'%}"></script>
<script src="{% static 'service-js/main.js'%}"></script>
<!-- slider script -->


<!-- search script -->

<!-- searcg script -->
<script>
    var textPresetVal = new Choices('#choices-text-preset-values',
    {
      removeItemButton: true,
    });

  </script>

templates/legal.html
<h1>asdasd</h1>

templates/orders.html
{%include "base.html"%}



<script src="https://kit.fontawesome.com/1f5dc7dc1f.js" crossorigin="anonymous"></script>

<style>
    .service-11 .font-weight-medium {
	font-weight: 500;
}

.service-11 .bg-light {
    background-color: #f4f8fa !important;
}

.service-11 .subtitle {
    color: #8d97ad;
    line-height: 24px;
}

.service-11 .card.card-shadow {
    -webkit-box-shadow: 0px 0px 30px rgba(115, 128, 157, 0.1);
    box-shadow: 0px 0px 30px rgba(115, 128, 157, 0.1);
}

.service-11 .wrap-service11-box {
  margin-top: 60px;
}

.service-11 .wrap-service11-box .icon-space {
  margin: -70px 0 20px;
}

.service-11 .wrap-service11-box .icon-space .icon-round {
  font-size: 45px;
  color: #ffffff;
}

.service-11 .bg-success-gradiant {
    background: #2cdd9b;
    background: -webkit-linear-gradient(legacy-direction(to right), #2cdd9b 0%, #1dc8cc 100%);
    background: -webkit-gradient(linear, left top, right top, from(#2cdd9b), to(#1dc8cc));
    background: -webkit-linear-gradient(left, #2cdd9b 0%, #1dc8cc 100%);
    background: -o-linear-gradient(left, #2cdd9b 0%, #1dc8cc 100%);
    background: linear-gradient(to right, #2cdd9b 0%, #1dc8cc 100%);
}

.service-11 .icon-round {
		width: 80px;
    line-height: 80px;
}

.service-11 .btn-success-gradiant {
		background: #2cdd9b;
    background: -webkit-linear-gradient(legacy-direction(to right), #2cdd9b 0%, #1dc8cc 100%);
    background: -webkit-gradient(linear, left top, right top, from(#2cdd9b), to(#1dc8cc));
    background: -webkit-linear-gradient(left, #2cdd9b 0%, #1dc8cc 100%);
    background: -o-linear-gradient(left, #2cdd9b 0%, #1dc8cc 100%);
    background: linear-gradient(to right, #2cdd9b 0%, #1dc8cc 100%);
}

.service-11 .btn-success-gradiant:hover {
		background: #1dc8cc;
    background: -webkit-linear-gradient(legacy-direction(to right), #1dc8cc 0%, #2cdd9b 100%);
    background: -webkit-gradient(linear, left top, right top, from(#1dc8cc), to(#2cdd9b));
    background: -webkit-linear-gradient(left, #1dc8cc 0%, #2cdd9b 100%);
    background: -o-linear-gradient(left, #1dc8cc 0%, #2cdd9b 100%);
    background: linear-gradient(to right, #1dc8cc 0%, #2cdd9b 100%);	
}

.service-11 .btn-md {
    padding: 15px 45px;
    font-size: 16px;
}
</style>


<section class="section core-value bg-tertiary">
    <div class="container">
        <div class="section-title">
            <h1>Your Orders</h1>
          </div>
        
        <div class="row align-items-center">
            
            <div class="col-lg-12">
                
                <div class="row position-relative gy-4">
                    {% for order in order %}
                    <div class="icon-box-item col-md-4">
                        <div class="block bg-white">
                            <div class="icon rounded"><i style="color: black; margin-top: 25px;" class="fa-solid fa-calendar-days"></i> </div>
                            <h3 class="mb-3">Name: {{order.services_required}}</h3>
                            
                            <h5 class="mb-3">Date: {{order.date}}</h3>
                            <h5 class="mb-3">Time: {{order.time}}</h3>
                                <p class="mb-3">Address: {{order.address}}</p>

                        </div>
                    </div>
                    {% endfor %}

                    
                   
                </div>
                
            </div>
            
        </div>
        
    </div>
</section>

{%include "footer.html"%}

templates/privacy-policy.html
privacy-policy.html

templates/search.html
{%include "base.html"%}

{% load crispy_forms_tags %} 

<form action="{% url 'booking:search' %}" method="post">
    
    {% csrf_token %}
    <input type="text" name="content"><br>


    <button>Sun</button>

</form>
{% for results in allPosts %}

<a href="{% url 'booking:services_detail' results.slug %}">{{results.title}}</a><br><br>
{{results.description}} <br><br>
<td>{{service_d.location}}</td><br>
<td>{{service_d.category}}</td><br>

{% empty %}

<p>No results found</p>

{% endfor %}<br><br><br><br><br><br>
{%include "footer.html"%}

templates/service_detail.html
{%include "base.html"%}
{% load crispy_forms_tags %} 


<style>
    .service-detail-image{
        border-radius: 20px;
        min-height: 20em;
        max-height: 20em;
  
    }
</style>



      
      <section class="section-sm">
          <div class="container">
              <div class="row g-5">
                  <div class="col-lg-6 mb-5 mb-lg-0">
                      <div class="bg-white shadow rounded-lg p-4 sticky-top" style="top: 30px;">
                          




    
                                            <div class="row">
                                                <div class="col-12 mb-4">
                                                    <h4>Book {{service_d.title}}</h4>
                                                   
                                                </div>
                                                <div class="col-lg-12">
                                                    <div class="contact-form">
                                                        <form action="" enctype="multipart/form-data" method="POST">
                                                            {% if user.is_authenticated %}
                                                            {% csrf_token %} 
                      
                                                            <div class="form-group mb-4 pb-2">
                                                                {{ form.date|as_crispy_field }}
                                                            </div>
                      
                                                            <div class="form-group mb-4 pb-2">
                                                                {{ form.time|as_crispy_field }}                                       
                                                             </div>
                    
                                                            <div class="form-group mb-4 pb-2">
                                                                {{ form.location|as_crispy_field }}                                       
                                                             </div>
                    
                                                            <div class="form-group mb-4 pb-2">
                                                                {{ form.address|as_crispy_field }}                                      
                                                             </div>
                    
                                                            <div class="form-group mb-4 pb-2">
                                                                {{ form.phone_no|as_crispy_field }}                                      
                                                             </div>
                    
                                                            <div class="form-group mb-4 pb-2">
                                                                {{ form.message|as_crispy_field }}                                      
                                                             </div>
                    
                                                             <input class="btn btn-primary w-100" type="submit" name="submit" value="Submit">
                                                            
                                                             {% else %}
                                                            {% csrf_token %}
                                                            <a href="{% url 'login' %}">Login before you book this service</a>
                                                            {% endif %}
                      
                                                        </form>
                    
                                                    </div>
                                                </div>
                                                
                                            </div>











                      </div>
                  </div>
                  <div class="col-lg-6">
                      <div class="content">
                        <img class="service-detail-image" src="/media/{{service_d.photo}}" alt=""><br><br>

                          <h3 id="heading-1">{{service_d.title}}</h3>
                          <p>{{service_d.description}}</p>
                          <h2 id="subheading-2">Service Details</h2>
                          <ul>
                              <li>Location: {{service_d.location}}</li>
                              <li>service category: {{service_d.category}}</li>

                          </ul>
                          <hr>
                         
                          
                      </div>
                  </div>
              </div>
          </div>
      </section>

   















    {%include "footer.html"%}

templates/service_list.html
{%include "base.html"%}
{% load static%}




<style>
    .rounded{
        min-height: 12em;
        max-height: 12em;
        min-width: 17em;
        max-width: 17em;
    }

   

</style>












<div class="bg-light py-3 service-13">
    <div class="container">
        <div class="section-title">
            <h1>ALL SERVICES </h1>
          </div>
        <!-- Row  -->
        <div class="row">
          
            <!-- Column -->
            {% for c in service %}

            <div class="col-lg-6 wrap-service13-box">
                <div class="card card-shadow border-0 mb-4">
										<div class="row no-gutters align-items-stretch">
												<div class="col-md-6 d-flex align-items-stretch">
														<img src="/media/{{c.photo}}" alt="wrapkit" class="img-fluid rounded" />
												</div>
												<div class="col-md-6 p-3 d-flex align-items-stretch">
													<div class="ml-2 p-3">
														<h3  class="font-weight-medium mt-2"><a style="color: rgb(31, 31, 31);" href="javascript:void(0)" class="linking">{{c.title}}</a></h3>
                                                        <a href="{% url 'booking:services_detail' c.slug %}" class="btn btn-primary mt-4" type="submit">Book service</a>
													</div>														
												</div>
										</div>
                </div>
            </div>
            {% endfor %}
            <!-- Column -->
            
						
        </div>
    </div>
</div>




{%include "footer.html"%}

templates/terms.html
terms.html