blog/urls.py
from django.urls import path
from .views import * 

urlpatterns = [
    path('' , blog , name="blog"),
    path('blog/<slug>' , blog_d , name="blog_detail"),
]

ecom/urls.py
from django.urls import path
from .views import * 

urlpatterns = [
    path('' , products , name="products"),
    path('product/<slug>' , products_d , name="products_detail"),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('booking.urls', 'booking'), namespace='booking')),
    path('ecom', include(('ecom.urls', 'ecom'), namespace='ecom')),
    path('blog', include(('blog.urls', 'blog'), namespace='blog')),
    path('accounts/', include('django.contrib.auth.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecom/models.py
from django.db import models
from django.utils.text import slugify

class Products(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    
    description = models.TextField(blank=True)
    image = models.ImageField()
    slug = models.SlugField(unique=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Products, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

ecom/views.py
from django.shortcuts import render,redirect
from .models import *

def products(request):
    items = Products.objects.all()

    return render(request, 'ecom/products_page.html', {'items': items})


def products_d(request, slug):
    product_d = Products.objects.filter(slug = slug).first()
    return render(request , 'ecom/product_detail.html' , {'product_d': product_d})

templates/ecom/product_detail.html
{%include "base.html"%}

<img src="/media/{{product_d.image}}" alt=""><br><br>
{{product_d.title}}<br><br>
{{product_d.price}}<br><br>
{{product_d.description}}<br><br>

{%include "footer.html"%}

templates/ecom/products_page.html
{%include "base.html"%}





<div class="card-deck">
    <div class="card">
        {% for products_list in items %}
      <img class="img-thumbnail" src="/media/{{products_list.image}}" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title"><a href="{% url 'ecom:products_detail' products_list.slug %}">{{ products_list.title }}</a></h5>
        <p class="card-text"><small class="text-muted">{{ products_list.price }}<</small></p>
        <p class="card-text">{{ products_list.description }}</p>
        
        {% endfor %}
      </div>
    </div>
  </div>

  {%include "footer.html"%}